### ISSUE TITLE
Unable to Mavenize existing project

### ISSUE THREAD

**Issue by surajdvrao85** [fastcube/tibco-bwmaven#1]
Hello,

I'm facing issue while executing BW mavenize which is unable to execute Mojo.
Also it will be helpful if you can provide document with screenshot to convert existing BW 5 project into Maven project.
There are couple of more issue such as:

It's creating folder structure by default even after modifying the pom
Also it's creating test cases and review folder even though it's not required
Also whole code is getting copied into target folder which I don't want to do.
New project is getting created into BW 7 format whereas I'm using BW 5.13.

**Comment by RadwaneMabchour** [comment]
Hello,

Actually you can't convert an existing BW 5 project into Maven Project, you should create another project following the steps in the [documentation](https://fastcube.github.io/tibco-factory/bw-maven-plugin/plugin-usage.html).
the test cases and review folders are for the upcoming plugins.
